"""iam: create users and refresh_tokens tables

Revision ID: 3d407b5ec230
Revises: 
Create Date: 2026-07-12 20:04:05.287592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3d407b5ec230'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=150), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.CHAR(length=26), nullable=False),
    sa.Column('organization_id', sa.CHAR(length=26), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('published_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox')),
    sa.UniqueConstraint('event_id', name=op.f('ux_outbox__event_id'))
    )
    op.create_table('users',
    sa.Column('organization_id', sa.CHAR(length=26), nullable=True),
    sa.Column('role', sa.Enum('founder', 'regional_manager', 'support_staff', 'finance_staff', 'org_admin', 'driver', 'parent', name='user_role'), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=32), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', 'invited', name='user_status'), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('created_by', sa.CHAR(length=26), nullable=True),
    sa.Column('updated_by', sa.CHAR(length=26), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.CheckConstraint("(role NOT IN ('org_admin', 'driver', 'parent')) OR (organization_id IS NOT NULL)", name=op.f('ck_users__org_scoped_role_requires_organization_id')),
    sa.CheckConstraint('email IS NOT NULL OR phone IS NOT NULL', name=op.f('ck_users__email_or_phone_present')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('ux_users__email')),
    sa.UniqueConstraint('phone', name=op.f('ux_users__phone'))
    )
    op.create_index(op.f('ix_users__organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users__role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users__status'), 'users', ['status'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.CHAR(length=26), nullable=False),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('issued_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('revoked_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('ux_refresh_tokens__token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens__expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens__user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # NOTE: autogenerate also proposed `op.drop_table('schools')` / `op.drop_table('students')`
    # here. Those tables pre-exist in this dev database from an unrelated prior use of the
    # `raad` schema name on this MySQL instance — they are not part of any approved RAAD
    # bounded context (Database Design has no `schools`/`students` tables; the approved
    # equivalents are `organizations` and `transport_ops.students`, neither implemented yet).
    # Left untouched deliberately, per explicit instruction not to modify schema outside IAM.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed recreating `schools`/`students` here (the mirror image
    # of the drops removed from `upgrade()` above) — omitted for the same reason: this
    # migration never touches those pre-existing, out-of-scope tables in either direction.
    # MySQL refuses to drop `ix_refresh_tokens__user_id` while it still backs the
    # `fk_refresh_tokens__users` FK (errno 1553) — the FK constraint must go first;
    # `drop_table` below then removes the remaining `ix_refresh_tokens__expires_at` index.
    op.drop_constraint('fk_refresh_tokens__users', 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens__user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens__expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users__status'), table_name='users')
    op.drop_index(op.f('ix_users__role'), table_name='users')
    op.drop_index(op.f('ix_users__organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('outbox')
    # ### end Alembic commands ###
