"""organization: create organizations and regions tables

Revision ID: 515fe8b7a640
Revises: 3d407b5ec230
Create Date: 2026-07-13 11:31:10.166469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "515fe8b7a640"
down_revision: Union[str, None] = "3d407b5ec230"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regions",
        sa.Column("name", sa.VARCHAR(length=120), nullable=False),
        sa.Column("geographic_scope", sa.VARCHAR(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="region_status"),
            nullable=False,
        ),
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("created_by", sa.CHAR(length=26), nullable=True),
        sa.Column("updated_by", sa.CHAR(length=26), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", mysql.DATETIME(fsp=3), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regions")),
        sa.UniqueConstraint("name", name=op.f("ux_regions__name")),
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("org_type", sa.Enum("school", name="org_type"), nullable=False),
        sa.Column("parent_org_id", sa.CHAR(length=26), nullable=True),
        sa.Column("region_id", sa.CHAR(length=26), nullable=False),
        sa.Column(
            "billing_model",
            sa.Enum("organization_pays", "parent_pays", name="billing_model"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "suspended", "inactive", name="organization_status"),
            nullable=False,
        ),
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False),
        sa.Column("created_by", sa.CHAR(length=26), nullable=True),
        sa.Column("updated_by", sa.CHAR(length=26), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", mysql.DATETIME(fsp=3), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_org_id"],
            ["organizations.id"],
            name=op.f("fk_organizations__organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["region_id"], ["regions.id"], name=op.f("fk_organizations__regions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(
        op.f("ix_organizations__parent_org_id"),
        "organizations",
        ["parent_org_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organizations__region_id"),
        "organizations",
        ["region_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organizations__status"), "organizations", ["status"], unique=False
    )
    # NOTE: autogenerate also proposed `op.drop_table('schools')` / `op.drop_table('students')`
    # here, for the same reason the prior migration's own note explains (3d407b5ec230): these
    # tables pre-exist in this dev database from an unrelated prior use of the `raad` schema
    # name and are not part of any approved RAAD bounded context. Left untouched deliberately.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed recreating `schools`/`students` here (the mirror image
    # of the drops removed from `upgrade()` above) — omitted for the same reason: this
    # migration never touches those pre-existing, out-of-scope tables in either direction.
    # MySQL refuses to drop `ix_organizations__parent_org_id`/`ix_organizations__region_id`
    # while they still back their respective FK constraints (errno 1553) — same fix as the
    # prior migration's `fk_refresh_tokens__users` note: drop both FKs first.
    op.drop_constraint(
        "fk_organizations__organizations", "organizations", type_="foreignkey"
    )
    op.drop_constraint("fk_organizations__regions", "organizations", type_="foreignkey")
    op.drop_index(op.f("ix_organizations__status"), table_name="organizations")
    op.drop_index(op.f("ix_organizations__region_id"), table_name="organizations")
    op.drop_index(op.f("ix_organizations__parent_org_id"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_table("regions")
    # ### end Alembic commands ###
