"""ERP finance: school_erp (C11) + platform_finance (C12), plan limits, transport_fees migration

ADR-0040. Three things in one migration, because they are one change:

1. **Nine new tables** — six for `school_erp` (Organization -> Student) and three for
   `platform_finance` (Vendor -> RAAD). Together with `billing` (RAAD -> Organization) that is
   three financial domains in three modules, which ADR-0038 §2 requires stay separate.
2. **`plans.device_limit` / `plans.user_limit`** — purely additive, nullable = unlimited,
   matching `vehicle_limit`'s existing meaning (ADR-0040 §4).
3. **`transport_fees` -> `erp_student_invoices`, then dropped.** ADR-0038 left this open; ADR-0040
   §2 resolves it as a migration rather than a dormant duplicate. Rows are copied with a status
   remap (`due->issued`, `paid->paid`, `overdue->overdue`, `waived->cancelled`) before the drop.

**`downgrade()` recreates `transport_fees` but cannot restore its rows** — data moved into
`erp_student_invoices` is not copied back, because a student invoice may since have received
payments and gained a discount, and there is no honest way to collapse that back into the old
four-column shape. The live table held zero rows when this ran, so the loss is theoretical here,
but it is stated rather than discovered later.

**Every new PostgreSQL ENUM is explicitly dropped in `downgrade()`.** `alembic revision
--autogenerate` never emits these itself, and omitting them breaks re-upgrade after a downgrade
with "type already exists" — a permanent rule in this repository (CLAUDE.md, Migration status).

Revision ID: 7387f1b2ee6a
Revises: c8b4d17e9f30
Create Date: 2026-09-05 11:22:04.426955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7387f1b2ee6a'
down_revision: Union[str, None] = 'c8b4d17e9f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_fee_plans',
    sa.Column('organization_id', sa.CHAR(length=26), nullable=False),
    sa.Column('name', sa.VARCHAR(length=160), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('default_discount_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='erp_fee_plan_status'), nullable=False),
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.CHAR(length=26), nullable=True),
    sa.Column('updated_by', sa.CHAR(length=26), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_fee_plans')),
    sa.UniqueConstraint('organization_id', 'name', name='ux_erp_fee_plans__org_name')
    )
    op.create_index('ix_erp_fee_plans__org_status', 'erp_fee_plans', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_erp_fee_plans__organization_id'), 'erp_fee_plans', ['organization_id'], unique=False)
    op.create_table('erp_financial_categories',
    sa.Column('organization_id', sa.CHAR(length=26), nullable=False),
    sa.Column('name', sa.VARCHAR(length=160), nullable=False),
    sa.Column('kind', sa.Enum('income', 'expense', name='erp_category_kind'), nullable=False),
    sa.Column('parent_category_id', sa.CHAR(length=26), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='erp_category_status'), nullable=False),
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.CHAR(length=26), nullable=True),
    sa.Column('updated_by', sa.CHAR(length=26), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['erp_financial_categories.id'], name=op.f('fk_erp_financial_categories__erp_financial_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_financial_categories')),
    sa.UniqueConstraint('organization_id', 'kind', 'name', name='ux_erp_financial_categories__org_kind_name')
    )
    op.create_index('ix_erp_financial_categories__org_kind', 'erp_financial_categories', ['organization_id', 'kind'], unique=False)
    op.create_index(op.f('ix_erp_financial_categories__organization_id'), 'erp_financial_categories', ['organization_id'], unique=False)
    op.create_table('platform_financial_categories',
    sa.Column('name', sa.VARCHAR(length=160), nullable=False),
    sa.Column('kind', sa.Enum('income', 'expense', name='platform_category_kind'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='platform_category_status'), nullable=False),
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.CHAR(length=26), nullable=True),
    sa.Column('updated_by', sa.CHAR(length=26), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_financial_categories'))
    )
    op.create_index('ix_platform_financial_categories__kind', 'platform_financial_categories', ['kind'], unique=False)
    op.create_table('erp_expenses',
    sa.Column('organization_id', sa.CHAR(length=26), nullable=False),
    sa.Column('category_id', sa.CHAR(length=26), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('occurred_on', sa.DATE(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference', sa.VARCHAR(length=120), nullable=True),
    sa.Column('vehicle_id', sa.CHAR(length=26), nullable=True),
    sa.Column('attachment_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_voided', sa.Boolean(), nullable=False),
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.CHAR(length=26), nullable=True),
    sa.Column('updated_by', sa.CHAR(length=26), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['erp_financial_categories.id'], name=op.f('fk_erp_expenses__erp_financial_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_expenses'))
    )
    op.create_index('ix_erp_expenses__org_occurred', 'erp_expenses', ['organization_id', 'occurred_on'], unique=False)
    op.create_index('ix_erp_expenses__org_vehicle', 'erp_expenses', ['organization_id', 'vehicle_id'], unique=False)
    op.create_index(op.f('ix_erp_expenses__organization_id'), 'erp_expenses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_erp_expenses__vehicle_id'), 'erp_expenses', ['vehicle_id'], unique=False)
    op.create_table('erp_income',
    sa.Column('organization_id', sa.CHAR(length=26), nullable=False),
    sa.Column('category_id', sa.CHAR(length=26), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('occurred_on', sa.DATE(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference', sa.VARCHAR(length=120), nullable=True),
    sa.Column('attachment_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_voided', sa.Boolean(), nullable=False),
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.CHAR(length=26), nullable=True),
    sa.Column('updated_by', sa.CHAR(length=26), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['erp_financial_categories.id'], name=op.f('fk_erp_income__erp_financial_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_income'))
    )
    op.create_index('ix_erp_income__org_occurred', 'erp_income', ['organization_id', 'occurred_on'], unique=False)
    op.create_index(op.f('ix_erp_income__organization_id'), 'erp_income', ['organization_id'], unique=False)
    op.create_table('erp_student_invoices',
    sa.Column('organization_id', sa.CHAR(length=26), nullable=False),
    sa.Column('student_id', sa.CHAR(length=26), nullable=False),
    sa.Column('fee_plan_id', sa.CHAR(length=26), nullable=True),
    sa.Column('period', sa.CHAR(length=7), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'issued', 'partially_paid', 'paid', 'overdue', 'cancelled', name='erp_student_invoice_status'), nullable=False),
    sa.Column('route_id', sa.CHAR(length=26), nullable=True),
    sa.Column('vehicle_id', sa.CHAR(length=26), nullable=True),
    sa.Column('driver_id', sa.CHAR(length=26), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.CHAR(length=26), nullable=True),
    sa.Column('updated_by', sa.CHAR(length=26), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fee_plan_id'], ['erp_fee_plans.id'], name=op.f('fk_erp_student_invoices__erp_fee_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_student_invoices')),
    sa.UniqueConstraint('student_id', 'period', name='ux_erp_student_invoices__student_period')
    )
    op.create_index('ix_erp_student_invoices__org_status_due', 'erp_student_invoices', ['organization_id', 'status', 'due_date'], unique=False)
    op.create_index('ix_erp_student_invoices__org_vehicle_period', 'erp_student_invoices', ['organization_id', 'vehicle_id', 'period'], unique=False)
    op.create_index(op.f('ix_erp_student_invoices__organization_id'), 'erp_student_invoices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_erp_student_invoices__student_id'), 'erp_student_invoices', ['student_id'], unique=False)
    op.create_index(op.f('ix_erp_student_invoices__vehicle_id'), 'erp_student_invoices', ['vehicle_id'], unique=False)
    op.create_table('platform_expenses',
    sa.Column('kind', sa.Enum('salaries', 'rent', 'electricity', 'water', 'internet', 'equipment', 'maintenance', 'fuel', 'marketing', 'travel', 'software', 'professional_fees', 'taxes', 'other', name='platform_expense_kind'), nullable=False),
    sa.Column('category_id', sa.CHAR(length=26), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('occurred_on', sa.DATE(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vendor', sa.VARCHAR(length=160), nullable=True),
    sa.Column('reference', sa.VARCHAR(length=120), nullable=True),
    sa.Column('attachment_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_voided', sa.Boolean(), nullable=False),
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.CHAR(length=26), nullable=True),
    sa.Column('updated_by', sa.CHAR(length=26), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['platform_financial_categories.id'], name=op.f('fk_platform_expenses__platform_financial_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_expenses'))
    )
    op.create_index('ix_platform_expenses__occurred_kind', 'platform_expenses', ['occurred_on', 'kind'], unique=False)
    op.create_table('platform_income',
    sa.Column('kind', sa.Enum('subscription', 'hardware_sale', 'installation', 'support_contract', 'grant', 'other', name='platform_income_kind'), nullable=False),
    sa.Column('category_id', sa.CHAR(length=26), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('occurred_on', sa.DATE(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=160), nullable=True),
    sa.Column('reference', sa.VARCHAR(length=120), nullable=True),
    sa.Column('is_voided', sa.Boolean(), nullable=False),
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.CHAR(length=26), nullable=True),
    sa.Column('updated_by', sa.CHAR(length=26), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['platform_financial_categories.id'], name=op.f('fk_platform_income__platform_financial_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_income'))
    )
    op.create_index('ix_platform_income__occurred_kind', 'platform_income', ['occurred_on', 'kind'], unique=False)
    op.create_table('erp_student_payments',
    sa.Column('organization_id', sa.CHAR(length=26), nullable=False),
    sa.Column('invoice_id', sa.CHAR(length=26), nullable=False),
    sa.Column('student_id', sa.CHAR(length=26), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('method', sa.Enum('cash', 'bank_transfer', 'mobile_money', 'cheque', 'card', 'other', name='erp_student_payment_method'), nullable=False),
    sa.Column('reference', sa.VARCHAR(length=120), nullable=True),
    sa.Column('received_on', sa.DATE(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_voided', sa.Boolean(), nullable=False),
    sa.Column('voided_reason', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.CHAR(length=26), nullable=True),
    sa.Column('updated_by', sa.CHAR(length=26), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['erp_student_invoices.id'], name=op.f('fk_erp_student_payments__erp_student_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_student_payments'))
    )
    op.create_index(op.f('ix_erp_student_payments__invoice_id'), 'erp_student_payments', ['invoice_id'], unique=False)
    op.create_index('ix_erp_student_payments__org_received', 'erp_student_payments', ['organization_id', 'received_on'], unique=False)
    op.create_index(op.f('ix_erp_student_payments__organization_id'), 'erp_student_payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_erp_student_payments__student_id'), 'erp_student_payments', ['student_id'], unique=False)
    # ADR-0040 §2 — move school->student fees into their new home before dropping the old table.
    #
    # `id` is preserved so any external reference to a fee id keeps resolving. `period` is
    # normalised to the `YYYY-MM` shape `BillingPeriod` validates: `transport_fees.period` was a
    # free-form 20-char label, so anything that is not already `YYYY-MM` is skipped rather than
    # guessed at — a mangled period would fail `BillingPeriod` validation on the first read and
    # be far harder to diagnose than a row that was never copied.
    #
    # `due_date` has no source column at all (`transport_fees` had none), so it is derived as the
    # last day of the billing period — the only defensible reading of "this month's fee is due".
    op.execute(
        """
        INSERT INTO erp_student_invoices (
            id, organization_id, student_id, fee_plan_id, period,
            amount, discount_amount, amount_paid, currency, due_date, status,
            route_id, vehicle_id, driver_id, notes, issued_at, paid_at,
            created_at, updated_at, created_by, updated_by, row_version, deleted_at
        )
        SELECT
            tf.id,
            tf.organization_id,
            tf.student_id,
            NULL,
            tf.period,
            tf.amount,
            0.00,
            CASE WHEN tf.status = 'paid' THEN tf.amount ELSE 0.00 END,
            tf.currency,
            (date_trunc('month', to_date(tf.period, 'YYYY-MM')) + interval '1 month - 1 day')::date,
            CASE tf.status
                WHEN 'due'     THEN 'issued'
                WHEN 'paid'    THEN 'paid'
                WHEN 'overdue' THEN 'overdue'
                WHEN 'waived'  THEN 'cancelled'
                ELSE 'issued'
            END::erp_student_invoice_status,
            NULL, NULL, NULL,
            'Migrated from transport_fees (ADR-0040)',
            tf.created_at,
            CASE WHEN tf.status = 'paid' THEN tf.updated_at ELSE NULL END,
            tf.created_at,
            tf.updated_at,
            tf.created_by,
            tf.updated_by,
            tf.row_version,
            tf.deleted_at
        FROM transport_fees tf
        WHERE tf.period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'
        """
    )

    op.drop_index(op.f('ix_transport_fees__organization_id'), table_name='transport_fees')
    op.drop_index(op.f('ix_transport_fees__status'), table_name='transport_fees')
    op.drop_index(op.f('ix_transport_fees__student_id'), table_name='transport_fees')
    op.drop_table('transport_fees')
    # The enum outlives its table unless dropped explicitly.
    op.execute("DROP TYPE IF EXISTS transport_fee_status")

    op.add_column('plans', sa.Column('device_limit', sa.Integer(), nullable=True))
    op.add_column('plans', sa.Column('user_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'user_limit')
    op.drop_column('plans', 'device_limit')
    # No explicit `CREATE TYPE` here: `postgresql.ENUM` inside the `create_table` below emits
    # one itself, and adding a second raises DuplicateObjectError. (The *upgrade* direction does
    # need its explicit `DROP TYPE` — `drop_table` does not remove the type.)
    op.create_table('transport_fees',
    sa.Column('organization_id', sa.CHAR(length=26), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.CHAR(length=26), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.CHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('due', 'paid', 'overdue', 'waived', name='transport_fee_status'), autoincrement=False, nullable=False),
    sa.Column('id', sa.CHAR(length=26), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.CHAR(length=26), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.CHAR(length=26), autoincrement=False, nullable=True),
    sa.Column('row_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transport_fees'))
    )
    op.create_index(op.f('ix_transport_fees__student_id'), 'transport_fees', ['student_id'], unique=False)
    op.create_index(op.f('ix_transport_fees__status'), 'transport_fees', ['status'], unique=False)
    op.create_index(op.f('ix_transport_fees__organization_id'), 'transport_fees', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_erp_student_payments__student_id'), table_name='erp_student_payments')
    op.drop_index(op.f('ix_erp_student_payments__organization_id'), table_name='erp_student_payments')
    op.drop_index('ix_erp_student_payments__org_received', table_name='erp_student_payments')
    op.drop_index(op.f('ix_erp_student_payments__invoice_id'), table_name='erp_student_payments')
    op.drop_table('erp_student_payments')
    op.drop_index('ix_platform_income__occurred_kind', table_name='platform_income')
    op.drop_table('platform_income')
    op.drop_index('ix_platform_expenses__occurred_kind', table_name='platform_expenses')
    op.drop_table('platform_expenses')
    op.drop_index(op.f('ix_erp_student_invoices__vehicle_id'), table_name='erp_student_invoices')
    op.drop_index(op.f('ix_erp_student_invoices__student_id'), table_name='erp_student_invoices')
    op.drop_index(op.f('ix_erp_student_invoices__organization_id'), table_name='erp_student_invoices')
    op.drop_index('ix_erp_student_invoices__org_vehicle_period', table_name='erp_student_invoices')
    op.drop_index('ix_erp_student_invoices__org_status_due', table_name='erp_student_invoices')
    op.drop_table('erp_student_invoices')
    op.drop_index(op.f('ix_erp_income__organization_id'), table_name='erp_income')
    op.drop_index('ix_erp_income__org_occurred', table_name='erp_income')
    op.drop_table('erp_income')
    op.drop_index(op.f('ix_erp_expenses__vehicle_id'), table_name='erp_expenses')
    op.drop_index(op.f('ix_erp_expenses__organization_id'), table_name='erp_expenses')
    op.drop_index('ix_erp_expenses__org_vehicle', table_name='erp_expenses')
    op.drop_index('ix_erp_expenses__org_occurred', table_name='erp_expenses')
    op.drop_table('erp_expenses')
    op.drop_index('ix_platform_financial_categories__kind', table_name='platform_financial_categories')
    op.drop_table('platform_financial_categories')
    op.drop_index(op.f('ix_erp_financial_categories__organization_id'), table_name='erp_financial_categories')
    op.drop_index('ix_erp_financial_categories__org_kind', table_name='erp_financial_categories')
    op.drop_table('erp_financial_categories')
    op.drop_index(op.f('ix_erp_fee_plans__organization_id'), table_name='erp_fee_plans')
    op.drop_index('ix_erp_fee_plans__org_status', table_name='erp_fee_plans')
    op.drop_table('erp_fee_plans')
    # ### end Alembic commands ###

    # Every ENUM this migration created, dropped explicitly — `--autogenerate` never emits these,
    # and leaving them behind makes a re-upgrade fail with "type already exists".
    for enum_name in (
        "erp_category_kind",
        "erp_category_status",
        "erp_fee_plan_status",
        "erp_student_invoice_status",
        "erp_student_payment_method",
        "platform_category_kind",
        "platform_category_status",
        "platform_expense_kind",
        "platform_income_kind",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
