"""transport_ops: create student_parents table

Revision ID: ff41b1f3c61c
Revises: 4b43a835fc86
Create Date: 2026-07-17 22:22:27.228226

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ff41b1f3c61c"
down_revision: Union[str, None] = "4b43a835fc86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_parents",
        sa.Column("student_id", sa.CHAR(length=26), nullable=False),
        sa.Column("parent_id", sa.CHAR(length=26), nullable=False),
        sa.Column("relationship", sa.VARCHAR(length=40), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["parents.id"], name=op.f("fk_student_parents__parents")
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.id"], name=op.f("fk_student_parents__students")
        ),
        sa.PrimaryKeyConstraint(
            "student_id", "parent_id", name=op.f("pk_student_parents")
        ),
    )
    op.create_index(
        op.f("ix_student_parents__parent_id"),
        "student_parents",
        ["parent_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_student_parents__parent_id"), table_name="student_parents")
    op.drop_table("student_parents")
    # ### end Alembic commands ###
