"""transport_ops: create routes and stops tables

Revision ID: 71b67f0e5709
Revises: 8bde77c847c0
Create Date: 2026-07-18 19:36:50.509246

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "71b67f0e5709"
down_revision: Union[str, None] = "8bde77c847c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routes",
        sa.Column("organization_id", sa.CHAR(length=26), nullable=False),
        sa.Column("name", sa.VARCHAR(length=160), nullable=False),
        sa.Column(
            "status", sa.Enum("active", "inactive", name="route_status"), nullable=False
        ),
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.CHAR(length=26), nullable=True),
        sa.Column("updated_by", sa.CHAR(length=26), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routes")),
        sa.UniqueConstraint(
            "organization_id", "name", name=op.f("ux_routes__organization_id_name")
        ),
    )
    op.create_index(
        op.f("ix_routes__organization_id"), "routes", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_routes__status"), "routes", ["status"], unique=False)
    op.create_table(
        "stops",
        sa.Column("organization_id", sa.CHAR(length=26), nullable=False),
        sa.Column("route_id", sa.CHAR(length=26), nullable=False),
        sa.Column("name", sa.VARCHAR(length=160), nullable=False),
        sa.Column(
            "latitude",
            sa.DECIMAL(precision=9, scale=6, asdecimal=False),
            nullable=False,
        ),
        sa.Column(
            "longitude",
            sa.DECIMAL(precision=9, scale=6, asdecimal=False),
            nullable=False,
        ),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("geofence_radius_m", sa.Integer(), nullable=True),
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.CHAR(length=26), nullable=True),
        sa.Column("updated_by", sa.CHAR(length=26), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["route_id"], ["routes.id"], name=op.f("fk_stops__routes")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stops")),
        sa.UniqueConstraint(
            "route_id", "sequence_no", name=op.f("ux_stops__route_id_sequence_no")
        ),
    )
    op.create_index(
        op.f("ix_stops__organization_id"), "stops", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_stops__route_id"), "stops", ["route_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stops__route_id"), table_name="stops")
    op.drop_index(op.f("ix_stops__organization_id"), table_name="stops")
    op.drop_table("stops")
    op.drop_index(op.f("ix_routes__status"), table_name="routes")
    op.drop_index(op.f("ix_routes__organization_id"), table_name="routes")
    op.drop_table("routes")
    # ### end Alembic commands ###
    # PostgreSQL native ENUM types outlive their owning table's DROP (ADR-0002) and must be
    # dropped explicitly, or a later re-upgrade's CREATE TYPE collides with the orphaned one.
    # `autogenerate` does not emit this; added by hand (see 8ffa6434d344 for the same fix).
    sa.Enum(name="route_status").drop(op.get_bind(), checkfirst=True)
