"""transport_ops: create drivers table

Revision ID: 8bde77c847c0
Revises: ff41b1f3c61c
Create Date: 2026-07-18 19:08:34.529558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8bde77c847c0"
down_revision: Union[str, None] = "ff41b1f3c61c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drivers",
        sa.Column("organization_id", sa.CHAR(length=26), nullable=False),
        sa.Column("user_id", sa.CHAR(length=26), nullable=False),
        sa.Column("license_no", sa.VARCHAR(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="driver_status"),
            nullable=False,
        ),
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.CHAR(length=26), nullable=True),
        sa.Column("updated_by", sa.CHAR(length=26), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drivers")),
    )
    op.create_index(
        op.f("ix_drivers__organization_id"),
        "drivers",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_drivers__status"), "drivers", ["status"], unique=False)
    op.create_index(op.f("ix_drivers__user_id"), "drivers", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_drivers__user_id"), table_name="drivers")
    op.drop_index(op.f("ix_drivers__status"), table_name="drivers")
    op.drop_index(op.f("ix_drivers__organization_id"), table_name="drivers")
    op.drop_table("drivers")
    # ### end Alembic commands ###
    # PostgreSQL native ENUM types outlive their owning table's DROP (ADR-0002) and must be
    # dropped explicitly, or a later re-upgrade's CREATE TYPE collides with the orphaned one.
    # `autogenerate` does not emit this; added by hand (see 8ffa6434d344 for the same fix).
    sa.Enum(name="driver_status").drop(op.get_bind(), checkfirst=True)
