"""tracking: create vehicle_positions and geofence_events tables

Revision ID: 8589ef0ab6bb
Revises: 9e901ca06186
Create Date: 2026-07-17 16:46:20.861762

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8589ef0ab6bb"
down_revision: Union[str, None] = "9e901ca06186"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geofence_events",
        sa.Column("organization_id", sa.CHAR(length=26), nullable=False),
        sa.Column("trip_id", sa.CHAR(length=26), nullable=False),
        sa.Column("stop_id", sa.CHAR(length=26), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "approaching_stop",
                "entered_stop",
                "arrived_org",
                "exited",
                name="geofence_event_type",
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_geofence_events")),
    )
    op.create_index(
        "ix_geofence_events__trip_id_occurred_at",
        "geofence_events",
        ["trip_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "vehicle_positions",
        sa.Column("organization_id", sa.CHAR(length=26), nullable=False),
        sa.Column("vehicle_id", sa.CHAR(length=26), nullable=False),
        sa.Column("device_id", sa.CHAR(length=26), nullable=False),
        sa.Column("trip_id", sa.CHAR(length=26), nullable=True),
        sa.Column(
            "latitude",
            sa.DECIMAL(precision=9, scale=6, asdecimal=False),
            nullable=False,
        ),
        sa.Column(
            "longitude",
            sa.DECIMAL(precision=9, scale=6, asdecimal=False),
            nullable=False,
        ),
        sa.Column("speed_kph", sa.SmallInteger(), nullable=True),
        sa.Column("heading_deg", sa.SmallInteger(), nullable=True),
        sa.Column("alarm_flags", sa.Integer(), nullable=True),
        sa.Column("is_backfill", sa.Boolean(), nullable=False),
        sa.Column("event_time", sa.DateTime(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.PrimaryKeyConstraint("event_time", "id", name=op.f("pk_vehicle_positions")),
    )
    op.create_index(
        op.f("ix_vehicle_positions__organization_id"),
        "vehicle_positions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_vehicle_positions__trip_id_event_time",
        "vehicle_positions",
        ["trip_id", "event_time"],
        unique=False,
    )
    op.create_index(
        "ix_vehicle_positions__vehicle_id_event_time",
        "vehicle_positions",
        ["vehicle_id", "event_time"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_vehicle_positions__vehicle_id_event_time", table_name="vehicle_positions"
    )
    op.drop_index(
        "ix_vehicle_positions__trip_id_event_time", table_name="vehicle_positions"
    )
    op.drop_index(
        op.f("ix_vehicle_positions__organization_id"), table_name="vehicle_positions"
    )
    op.drop_table("vehicle_positions")
    op.drop_index(
        "ix_geofence_events__trip_id_occurred_at", table_name="geofence_events"
    )
    op.drop_table("geofence_events")
    # ### end Alembic commands ###
    # PostgreSQL native ENUM types outlive their owning table's DROP (ADR-0002) and must be
    # dropped explicitly, or a later re-upgrade's CREATE TYPE collides with the orphaned one.
    # `autogenerate` does not emit this; added by hand (see 8ffa6434d344 for the same fix).
    sa.Enum(name="geofence_event_type").drop(op.get_bind(), checkfirst=True)
