"""transport_ops: create parents table

Revision ID: 4b43a835fc86
Revises: ed48df51b591
Create Date: 2026-07-17 21:38:46.292720

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4b43a835fc86"
down_revision: Union[str, None] = "ed48df51b591"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parents",
        sa.Column("organization_id", sa.CHAR(length=26), nullable=False),
        sa.Column("user_id", sa.CHAR(length=26), nullable=False),
        sa.Column("full_name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("phone", sa.VARCHAR(length=32), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="parent_status"),
            nullable=False,
        ),
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.CHAR(length=26), nullable=True),
        sa.Column("updated_by", sa.CHAR(length=26), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parents")),
    )
    op.create_index(
        op.f("ix_parents__organization_id"),
        "parents",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_parents__status"), "parents", ["status"], unique=False)
    op.create_index(op.f("ix_parents__user_id"), "parents", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parents__user_id"), table_name="parents")
    op.drop_index(op.f("ix_parents__status"), table_name="parents")
    op.drop_index(op.f("ix_parents__organization_id"), table_name="parents")
    op.drop_table("parents")
    # ### end Alembic commands ###
    # PostgreSQL native ENUM types outlive their owning table's DROP (ADR-0002) and must be
    # dropped explicitly, or a later re-upgrade's CREATE TYPE collides with the orphaned one.
    # `autogenerate` does not emit this; added by hand (see 8ffa6434d344 for the same fix).
    sa.Enum(name="parent_status").drop(op.get_bind(), checkfirst=True)
