"""transport_ops: create students table

Revision ID: ed48df51b591
Revises: 8589ef0ab6bb
Create Date: 2026-07-17 19:17:50.200267

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ed48df51b591"
down_revision: Union[str, None] = "8589ef0ab6bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "students",
        sa.Column("organization_id", sa.CHAR(length=26), nullable=False),
        sa.Column("full_name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("external_ref", sa.VARCHAR(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active", "disabled", "graduated", "transferred", name="student_status"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.CHAR(length=26), nullable=True),
        sa.Column("updated_by", sa.CHAR(length=26), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
    )
    op.create_index(
        op.f("ix_students__organization_id"),
        "students",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_students__status"), "students", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_students__status"), table_name="students")
    op.drop_index(op.f("ix_students__organization_id"), table_name="students")
    op.drop_table("students")
    # ### end Alembic commands ###
    # PostgreSQL native ENUM types outlive their owning table's DROP (ADR-0002) and must be
    # dropped explicitly, or a later re-upgrade's CREATE TYPE collides with the orphaned one.
    # `autogenerate` does not emit this; added by hand (see 8ffa6434d344 for the same fix).
    sa.Enum(name="student_status").drop(op.get_bind(), checkfirst=True)
