"""tracking: create vehicle_positions and geofence_events tables

Revision ID: a74d65d4fccf
Revises: 1fcf588d8ff7
Create Date: 2026-07-15 11:50:28.647648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a74d65d4fccf'
down_revision: Union[str, None] = '1fcf588d8ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geofence_events',
    sa.Column('organization_id', sa.CHAR(length=26), nullable=False),
    sa.Column('trip_id', sa.CHAR(length=26), nullable=False),
    sa.Column('stop_id', sa.CHAR(length=26), nullable=True),
    sa.Column('event_type', sa.Enum('approaching_stop', 'entered_stop', 'arrived_org', 'exited', name='geofence_event_type'), nullable=False),
    sa.Column('occurred_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geofence_events'))
    )
    op.create_index('ix_geofence_events__trip_id_occurred_at', 'geofence_events', ['trip_id', 'occurred_at'], unique=False)
    op.create_table('vehicle_positions',
    sa.Column('organization_id', sa.CHAR(length=26), nullable=False),
    sa.Column('vehicle_id', sa.CHAR(length=26), nullable=False),
    sa.Column('device_id', sa.CHAR(length=26), nullable=False),
    sa.Column('trip_id', sa.CHAR(length=26), nullable=True),
    sa.Column('latitude', mysql.DECIMAL(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('longitude', mysql.DECIMAL(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('speed_kph', sa.SmallInteger(), nullable=True),
    sa.Column('heading_deg', sa.SmallInteger(), nullable=True),
    sa.Column('alarm_flags', sa.Integer(), nullable=True),
    sa.Column('is_backfill', sa.Boolean(), nullable=False),
    sa.Column('event_time', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('received_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.PrimaryKeyConstraint('event_time', 'id', name=op.f('pk_vehicle_positions'))
    )
    op.create_index(op.f('ix_vehicle_positions__organization_id'), 'vehicle_positions', ['organization_id'], unique=False)
    op.create_index('ix_vehicle_positions__trip_id_event_time', 'vehicle_positions', ['trip_id', 'event_time'], unique=False)
    op.create_index('ix_vehicle_positions__vehicle_id_event_time', 'vehicle_positions', ['vehicle_id', 'event_time'], unique=False)
    # NOTE: autogenerate also proposed `op.drop_table('students')` / `op.drop_table('schools')`
    # here, for the same reason the prior migrations' own notes explain (3d407b5ec230,
    # 515fe8b7a640, 1fcf588d8ff7): these tables pre-exist in this dev database from an
    # unrelated prior use of the `raad` schema name and are not part of any approved RAAD
    # bounded context. Left untouched deliberately.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed recreating `schools`/`students` here (the mirror image
    # of the drops removed from `upgrade()` above) — omitted for the same reason: this
    # migration never touches those pre-existing, out-of-scope tables in either direction.
    # Neither `vehicle_positions` nor `geofence_events` declares a Foreign Key (both own only
    # cross-module reference columns, Database Design §11.3), so — unlike `515fe8b7a640` and
    # `1fcf588d8ff7` — there is no FK-backed-index drop ordering issue here; indexes and tables
    # can be dropped straightforwardly.
    op.drop_index('ix_vehicle_positions__vehicle_id_event_time', table_name='vehicle_positions')
    op.drop_index('ix_vehicle_positions__trip_id_event_time', table_name='vehicle_positions')
    op.drop_index(op.f('ix_vehicle_positions__organization_id'), table_name='vehicle_positions')
    op.drop_table('vehicle_positions')
    op.drop_index('ix_geofence_events__trip_id_occurred_at', table_name='geofence_events')
    op.drop_table('geofence_events')
    # ### end Alembic commands ###
