"""fleet_device: create vehicles devices cameras device_assignments tables

Revision ID: 1fcf588d8ff7
Revises: 515fe8b7a640
Create Date: 2026-07-14 18:16:21.083327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1fcf588d8ff7'
down_revision: Union[str, None] = '515fe8b7a640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('organization_id', sa.CHAR(length=26), nullable=False),
    sa.Column('terminal_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('model', sa.VARCHAR(length=120), nullable=True),
    sa.Column('vendor', sa.VARCHAR(length=120), nullable=True),
    sa.Column('sim_msisdn', sa.VARCHAR(length=32), nullable=True),
    sa.Column('lifecycle_state', sa.Enum('registered', 'activated', 'assigned', 'suspended', 'retired', name='device_lifecycle_state'), nullable=False),
    sa.Column('auth_key_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_seen_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('created_by', sa.CHAR(length=26), nullable=True),
    sa.Column('updated_by', sa.CHAR(length=26), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('terminal_id', name=op.f('ux_devices__terminal_id'))
    )
    op.create_index(op.f('ix_devices__lifecycle_state'), 'devices', ['lifecycle_state'], unique=False)
    op.create_index(op.f('ix_devices__organization_id'), 'devices', ['organization_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('organization_id', sa.CHAR(length=26), nullable=False),
    sa.Column('plate_no', sa.VARCHAR(length=32), nullable=False),
    sa.Column('label', sa.VARCHAR(length=120), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'maintenance', name='vehicle_status'), nullable=False),
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('created_by', sa.CHAR(length=26), nullable=True),
    sa.Column('updated_by', sa.CHAR(length=26), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles')),
    sa.UniqueConstraint('organization_id', 'plate_no', name=op.f('ux_vehicles__organization_id_plate_no'))
    )
    op.create_index(op.f('ix_vehicles__organization_id'), 'vehicles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_vehicles__status'), 'vehicles', ['status'], unique=False)
    op.create_table('cameras',
    sa.Column('organization_id', sa.CHAR(length=26), nullable=False),
    sa.Column('device_id', sa.CHAR(length=26), nullable=False),
    sa.Column('channel_no', sa.Integer(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=120), nullable=True),
    sa.Column('position', sa.Enum('in_cabin', 'road_facing', 'other', name='camera_position'), nullable=False),
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('created_by', sa.CHAR(length=26), nullable=True),
    sa.Column('updated_by', sa.CHAR(length=26), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_cameras__devices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras')),
    sa.UniqueConstraint('device_id', 'channel_no', name=op.f('ux_cameras__device_id_channel_no'))
    )
    op.create_index(op.f('ix_cameras__device_id'), 'cameras', ['device_id'], unique=False)
    op.create_index(op.f('ix_cameras__organization_id'), 'cameras', ['organization_id'], unique=False)
    op.create_table('device_assignments',
    sa.Column('organization_id', sa.CHAR(length=26), nullable=False),
    sa.Column('device_id', sa.CHAR(length=26), nullable=False),
    sa.Column('vehicle_id', sa.CHAR(length=26), nullable=False),
    sa.Column('assigned_by', sa.CHAR(length=26), nullable=True),
    sa.Column('assigned_at', mysql.DATETIME(fsp=3), nullable=False),
    sa.Column('unassigned_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('active_device_key', sa.CHAR(length=26), sa.Computed('(case when unassigned_at is null then device_id else null end)', persisted=True), nullable=True),
    sa.Column('active_vehicle_key', sa.CHAR(length=26), sa.Computed('(case when unassigned_at is null then vehicle_id else null end)', persisted=True), nullable=True),
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_assignments__devices')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_device_assignments__vehicles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_assignments')),
    sa.UniqueConstraint('active_device_key', name=op.f('ux_device_assignments__active_device_key')),
    sa.UniqueConstraint('active_vehicle_key', name=op.f('ux_device_assignments__active_vehicle_key'))
    )
    op.create_index(op.f('ix_device_assignments__device_id'), 'device_assignments', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_assignments__organization_id'), 'device_assignments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_device_assignments__vehicle_id'), 'device_assignments', ['vehicle_id'], unique=False)
    # NOTE: autogenerate also proposed `op.drop_table('students')` / `op.drop_table('schools')`
    # here, for the same reason the prior migrations' own notes explain (3d407b5ec230,
    # 515fe8b7a640): these tables pre-exist in this dev database from an unrelated prior use of
    # the `raad` schema name and are not part of any approved RAAD bounded context. Left
    # untouched deliberately.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed recreating `schools`/`students` here (the mirror image
    # of the drops removed from `upgrade()` above) — omitted for the same reason: this
    # migration never touches those pre-existing, out-of-scope tables in either direction.
    # MySQL refuses to drop `ix_device_assignments__device_id`/`ix_device_assignments__vehicle_id`
    # and `ix_cameras__device_id` while they still back their respective FK constraints (errno
    # 1553) — same fix as `515fe8b7a640`'s `fk_organizations__organizations` note: drop the FK
    # constraints first.
    op.drop_constraint(
        'fk_device_assignments__devices', 'device_assignments', type_='foreignkey'
    )
    op.drop_constraint(
        'fk_device_assignments__vehicles', 'device_assignments', type_='foreignkey'
    )
    op.drop_index(op.f('ix_device_assignments__vehicle_id'), table_name='device_assignments')
    op.drop_index(op.f('ix_device_assignments__organization_id'), table_name='device_assignments')
    op.drop_index(op.f('ix_device_assignments__device_id'), table_name='device_assignments')
    op.drop_table('device_assignments')
    op.drop_constraint('fk_cameras__devices', 'cameras', type_='foreignkey')
    op.drop_index(op.f('ix_cameras__organization_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras__device_id'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_vehicles__status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles__organization_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_devices__organization_id'), table_name='devices')
    op.drop_index(op.f('ix_devices__lifecycle_state'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
