"""fleet_device: create vehicles devices cameras device_assignments tables

Revision ID: 9e901ca06186
Revises: e42916138971
Create Date: 2026-07-17 16:02:47.903420

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9e901ca06186"
down_revision: Union[str, None] = "e42916138971"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("organization_id", sa.CHAR(length=26), nullable=False),
        sa.Column("terminal_id", sa.VARCHAR(length=64), nullable=False),
        sa.Column("model", sa.VARCHAR(length=120), nullable=True),
        sa.Column("vendor", sa.VARCHAR(length=120), nullable=True),
        sa.Column("sim_msisdn", sa.VARCHAR(length=32), nullable=True),
        sa.Column(
            "lifecycle_state",
            sa.Enum(
                "registered",
                "activated",
                "assigned",
                "suspended",
                "retired",
                name="device_lifecycle_state",
            ),
            nullable=False,
        ),
        sa.Column("auth_key_hash", sa.VARCHAR(length=255), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.CHAR(length=26), nullable=True),
        sa.Column("updated_by", sa.CHAR(length=26), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("terminal_id", name=op.f("ux_devices__terminal_id")),
    )
    op.create_index(
        op.f("ix_devices__lifecycle_state"),
        "devices",
        ["lifecycle_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_devices__organization_id"),
        "devices",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "vehicles",
        sa.Column("organization_id", sa.CHAR(length=26), nullable=False),
        sa.Column("plate_no", sa.VARCHAR(length=32), nullable=False),
        sa.Column("label", sa.VARCHAR(length=120), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", "maintenance", name="vehicle_status"),
            nullable=False,
        ),
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.CHAR(length=26), nullable=True),
        sa.Column("updated_by", sa.CHAR(length=26), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicles")),
        sa.UniqueConstraint(
            "organization_id",
            "plate_no",
            name=op.f("ux_vehicles__organization_id_plate_no"),
        ),
    )
    op.create_index(
        op.f("ix_vehicles__organization_id"),
        "vehicles",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_vehicles__status"), "vehicles", ["status"], unique=False)
    op.create_table(
        "cameras",
        sa.Column("organization_id", sa.CHAR(length=26), nullable=False),
        sa.Column("device_id", sa.CHAR(length=26), nullable=False),
        sa.Column("channel_no", sa.Integer(), nullable=False),
        sa.Column("label", sa.VARCHAR(length=120), nullable=True),
        sa.Column(
            "position",
            sa.Enum("in_cabin", "road_facing", "other", name="camera_position"),
            nullable=False,
        ),
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.CHAR(length=26), nullable=True),
        sa.Column("updated_by", sa.CHAR(length=26), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_cameras__devices")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cameras")),
        sa.UniqueConstraint(
            "device_id", "channel_no", name=op.f("ux_cameras__device_id_channel_no")
        ),
    )
    op.create_index(
        op.f("ix_cameras__device_id"), "cameras", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_cameras__organization_id"),
        "cameras",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "device_assignments",
        sa.Column("organization_id", sa.CHAR(length=26), nullable=False),
        sa.Column("device_id", sa.CHAR(length=26), nullable=False),
        sa.Column("vehicle_id", sa.CHAR(length=26), nullable=False),
        sa.Column("assigned_by", sa.CHAR(length=26), nullable=True),
        sa.Column("assigned_at", sa.DateTime(), nullable=False),
        sa.Column("unassigned_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_device_assignments__devices")
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_device_assignments__vehicles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_assignments")),
    )
    op.create_index(
        op.f("ix_device_assignments__device_id"),
        "device_assignments",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_assignments__organization_id"),
        "device_assignments",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_assignments__vehicle_id"),
        "device_assignments",
        ["vehicle_id"],
        unique=False,
    )
    op.create_index(
        "ux_device_assignments__active_device",
        "device_assignments",
        ["device_id"],
        unique=True,
        postgresql_where="unassigned_at IS NULL",
    )
    op.create_index(
        "ux_device_assignments__active_vehicle",
        "device_assignments",
        ["vehicle_id"],
        unique=True,
        postgresql_where="unassigned_at IS NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ux_device_assignments__active_vehicle",
        table_name="device_assignments",
        postgresql_where="unassigned_at IS NULL",
    )
    op.drop_index(
        "ux_device_assignments__active_device",
        table_name="device_assignments",
        postgresql_where="unassigned_at IS NULL",
    )
    op.drop_index(
        op.f("ix_device_assignments__vehicle_id"), table_name="device_assignments"
    )
    op.drop_index(
        op.f("ix_device_assignments__organization_id"), table_name="device_assignments"
    )
    op.drop_index(
        op.f("ix_device_assignments__device_id"), table_name="device_assignments"
    )
    op.drop_table("device_assignments")
    op.drop_index(op.f("ix_cameras__organization_id"), table_name="cameras")
    op.drop_index(op.f("ix_cameras__device_id"), table_name="cameras")
    op.drop_table("cameras")
    op.drop_index(op.f("ix_vehicles__status"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles__organization_id"), table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index(op.f("ix_devices__organization_id"), table_name="devices")
    op.drop_index(op.f("ix_devices__lifecycle_state"), table_name="devices")
    op.drop_table("devices")
    # ### end Alembic commands ###
    # PostgreSQL native ENUM types outlive their owning table's DROP (ADR-0002) and must be
    # dropped explicitly, or a later re-upgrade's CREATE TYPE collides with the orphaned one.
    # `autogenerate` does not emit this; added by hand (see 8ffa6434d344 for the same fix).
    sa.Enum(name="device_lifecycle_state").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="vehicle_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="camera_position").drop(op.get_bind(), checkfirst=True)
