"""organization: create organizations and regions tables

Revision ID: e42916138971
Revises: 8ffa6434d344
Create Date: 2026-07-17 16:02:03.110064

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e42916138971"
down_revision: Union[str, None] = "8ffa6434d344"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regions",
        sa.Column("name", sa.VARCHAR(length=120), nullable=False),
        sa.Column("geographic_scope", sa.VARCHAR(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="region_status"),
            nullable=False,
        ),
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.CHAR(length=26), nullable=True),
        sa.Column("updated_by", sa.CHAR(length=26), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regions")),
        sa.UniqueConstraint("name", name=op.f("ux_regions__name")),
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("org_type", sa.Enum("school", name="org_type"), nullable=False),
        sa.Column("parent_org_id", sa.CHAR(length=26), nullable=True),
        sa.Column("region_id", sa.CHAR(length=26), nullable=False),
        sa.Column(
            "billing_model",
            sa.Enum("organization_pays", "parent_pays", name="billing_model"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "suspended", "inactive", name="organization_status"),
            nullable=False,
        ),
        sa.Column("id", sa.CHAR(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.CHAR(length=26), nullable=True),
        sa.Column("updated_by", sa.CHAR(length=26), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_org_id"],
            ["organizations.id"],
            name=op.f("fk_organizations__organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["region_id"], ["regions.id"], name=op.f("fk_organizations__regions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(
        op.f("ix_organizations__parent_org_id"),
        "organizations",
        ["parent_org_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organizations__region_id"),
        "organizations",
        ["region_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organizations__status"), "organizations", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_organizations__status"), table_name="organizations")
    op.drop_index(op.f("ix_organizations__region_id"), table_name="organizations")
    op.drop_index(op.f("ix_organizations__parent_org_id"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_table("regions")
    # ### end Alembic commands ###
    # PostgreSQL native ENUM types outlive their owning table's DROP (ADR-0002) and must be
    # dropped explicitly, or a later re-upgrade's CREATE TYPE collides with the orphaned one.
    # `autogenerate` does not emit this; added by hand (see 8ffa6434d344 for the same fix).
    sa.Enum(name="org_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="billing_model").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="organization_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="region_status").drop(op.get_bind(), checkfirst=True)
